// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDww663O0F9O_ubtBQqzCi6G7opsg_ZQIo',
    appId: '1:555411380547:web:53693359a753f0f7d7b7f6',
    messagingSenderId: '555411380547',
    projectId: 'flash-chat-61a33',
    authDomain: 'flash-chat-61a33.firebaseapp.com',
    storageBucket: 'flash-chat-61a33.appspot.com',
    measurementId: 'G-HL1S5J31GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwtbo4oZfcTJnfZhPgTPCGi9zdV6BnR0',
    appId: '1:555411380547:android:94d646395b64c37dd7b7f6',
    messagingSenderId: '555411380547',
    projectId: 'flash-chat-61a33',
    storageBucket: 'flash-chat-61a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JZ39ptwc22lfrOk2fm4YLMs1SSokThs',
    appId: '1:555411380547:ios:375bfe565014d8b6d7b7f6',
    messagingSenderId: '555411380547',
    projectId: 'flash-chat-61a33',
    storageBucket: 'flash-chat-61a33.appspot.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
